
export const FETCH_CITY='FETCH_CITY';
export const ADD_CITY_VISITED='ADD_CITY_VISITED';
export const REMOVE_CITY_VISITED='REMOVE_CITY_VISITED';
export const GET_CITIES_VISITED='GET_CITIES_VISITED';

export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const LOGIN_USER_FAIL="LOGIN_USER_FAIL";
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL";
export const LOGOUT_REQUEST="LOGOUT_REQUEST";

